os:
  - linux
  - osx

language: node_js

node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  # io.js
  - "iojs-v1"
  - "iojs-v2"
  - "iojs"

branches:
  only:
  - master

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libasound2-dev

notifications:
  email: false

# Travis has no snd-dummy driver (https://github.com/travis-ci/travis-ci/issues/1754)
# preventing our tests from running. Instead we disable the default `npm install`
# installation step and run it as test script so compilation errors will mark the
# build as failed.
install:
  - case ${TRAVIS_NODE_VERSION} in
        iojs*)
            echo "Not upgrading npm for iojs."
            ;;
        *)
            npm update -g npm
            ;;
    esac

script:
  - export CXX=g++-4.8
  - npm install
