platform:
  - x86
  - x64

image:
  - Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    # io.js
    - nodejs_version: "1"
    - nodejs_version: "2"
    - nodejs_version: "3"

matrix:
  allow_failures:
    - nodejs_version: "2"
    - nodejs_version: "3"

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: >-
      if ($env:nodejs_version -eq "5") {
        npm -g install npm@3
      }
  - ps: >-
      if ($env:nodejs_version -eq "2" -Or $env:nodejs_version -eq "3") {
        npm -g update npm
      }
  - ps: >-
      if ($env:nodejs_version -eq "0.10") {
        npm -g install npm@3
        $env:PATH="$env:APPDATA\npm;$env:PATH"
      }
  - ps: >-
      if ($env:nodejs_version -eq "0.8") {
        npm config set strict-ssl false
        npm -g install npm@3
        $env:PATH="$env:APPDATA\npm;$env:PATH"
      }
  - npm install

test_script:
  - node --version
  - npm --version

deploy: off

build: off