platform:
  - x86
  - x64

image:
  - Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

deploy: off
build: off